### ISSUE TITLE
Handle possible notifications when window is restored

### ISSUE THREAD

**Issue by midopa** [yabirgb/punycodeAlert#3]
If the user restores a window that had a tab or multiple tabs with punycode URLs, then one or more notifications will appear. This is a bit suboptimal because:

1. Which tab the notification is talking about is ambiguous
2. If there were multiple tabs, then several notifications will appear

Possible solution:
- Group notifications together?

Is it possible to change the color of a tab? To indicate a possible warning? I couldn't find anything from a quick search on Google. If it's possible, then that can be done in lieu of multiple notifications for the window restore case.

**Comment by yabirgb** [comment]
I have solved the issue with multiple notifications using tags for them. Now only appears a notification for the tab you are looking at the moment. Is not possible to change tab icon
